# Set to the URL for your site
baseURL = "https://avatsav.dev"

# The name of this wonderful theme ;-).
theme = 'hugo-bearblog'

# Basic metadata configuration for your blog.
title = "Abhi right back"
author = "Abhijith Srivatsav"
copyright = "Copyright Â© 2026, Abhijith Srivatsav."
languageCode = "en-GB"

# Generate a nice robots.txt for SEO
enableRobotsTXT = true

# Generate "Bearblog"-like URLs !only!, see https://bearblog.dev/.
disableKinds = ["taxonomy"]
ignoreErrors = ["error-disable-taxonomy"]
[permalinks]
  blog = "/:slug/"
  tags = "/blog/:slug"

[params]
  # The "description" of your website. This is used in the meta data of your generated html.
  description = "Hi, hey, hello! ðŸ‘‹"

  # The path to your "favicon". This should be a square (at least 32px x 32px) png-file.
  # Hint: It's good practise to also put a "favicon.ico"-file into your "static"-folder.
  favicon = "images/favicon.svg"

  # Site name for OpenGraph
  title = "Abhi's devlog"

  # Optional: Default OG image for social sharing previews
  # ogImageDefault = "images/index.jpeg"

  # Optional: Twitter handle for Twitter Cards (without @)
  # twitter = "yourhandle"

  # This theme will, by default, inject a made-with-line at the bottom of the page.
  # You can turn it off, but we would really appreciate if you donâ€™t :-).
  # hideMadeWithLine = true

  # By default, if you want to read more than one blog post you have to always go
  # back to the /blog page.
  # By enabling this feature each blog post will have at the end a navigator
  # enablePostNavigator = true

  # By default, this theme displays dates with a format like "02 Jan, 2006", but
  # you can customize it by setting the `dateFormat` param in your site's config
  # file. See [Hugo's Format function docs](https://gohugo.io/functions/format/)
  # for details. An example TOML config that uses [ISO
  # 8601](https://en.wikipedia.org/wiki/ISO_8601) format:
  dateFormat = "02 Jan, 2006"

# Configure markup highlighter to match "Bearblog" aesthetics, see
# https://gohugo.io/configuration/markup/#highlight
[markup]
  [markup.highlight]
    style = 'rose-pine-moon' # https://xyproto.github.io/splash/docs/all.html
    noClasses = false
    lineNos = true
    lineNumbersInTable = false
    codeFences = true
  [markup.goldmark.renderer]
      unsafe = true
  [markup.goldmark.parser.attribute]
      block = true
